### PR TITLE
Fix translation location, enable auto-updates

### PR DESCRIPTION
**Pull request by bethac07**
The translation auto-push is built from ones I've done recently in some other repos, so should generally work, but obviously should test paths considering I apparently didn't do a good job of that last time!

### CODE REVIEW

**Comment by petebankhead** [comment]
I'm quite confused: did the last PR wrongly put things into `locale` instead of `locales`, and this fixes it?

Guess we need to match with https://github.com/bioimagebook/bioimagebook.github.io/blob/main/helpers/translate.py#L15
I remember understanding what `translate.py` did at the time, but I can barely relate to that person any more.

**Comment by bethac07** [comment]
>I'm quite confused: did the last PR wrongly put things into locale instead of locales, and this fixes it?

Yup, I messed up in #36 and put them in the wrong places, and one or both of us messed up in #33 (nearly certainly me) and specified the wrong place for Transifex to look for them

>I remember understanding what translate.py did at the time, but I can barely relate to that person any more

I win, because I forgot that you wrote it at all lol

**Comment by petebankhead** [comment]
Well, I remembered there was a reason for choosing `locales` but I didn't remember what it was until you reminded me about #33 
> Translations are added to `locales` instead of `locale`, because this is [now the default for locale_dirs](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-locale_dirs).

**Comment by petebankhead** [comment]
Are we good to merge if this builds?
And does a Spanish version exist anyway (even partially corrected) or am I rushing too far ahead...?

**Comment by bethac07** [comment]
>Are we good to merge if this builds?

I think so, though I can't be sure the GH action is going to behave as we want until we test it with edits to the actual book itself.

>And does a Spanish version exist anyway (even partially corrected) or am I rushing too far ahead...?

It doesn't, but it can! I was going to wait until the translation was finished or mostly-finished, but it need not be that order of operations

**Comment by petebankhead** [comment]
Merged with optimism!
Curious to see how the translated version looks - although Mariana's opinion could be decisive on this. Not sure if it's more motivating to see early while still translating, or to work towards a final big reveal occurring all at once.

**Pull request merged**
