### PR TITLE
Add support for translation via Transifex

### PR DESCRIPTION
**Pull request by bethac07**
This should prep the book to be ready to add translations. It seemed to build ok for me locally, but let's get CI on it!

### CODE REVIEW

**Comment by petebankhead** [comment]
Thanks @bethac07 !

It builds, but not quite as it should:

1. mybinder support has gone
   * Probably related: the total size of the build is much less; '_sources' is much smaller since it no only contains `.md` files and not companion `.ipynb` files
3. the image in the main index.html doesn't show up

I've just rebuilt from 'main' and confirmed that it is behaving properly, so I'm guessing the trouble arises from the switch from `_config.yml` to `conf.py`.

In fact, if I simply restore `_config.yml` (without deleting `conf.py`) then the build seems ok. Is that an option, or does `_config.yml`'s existence cause some other trouble somewhere?

**Comment by bethac07** [comment]
config.yml's existence AFAIK doesn't cause issues, I just don't know what happens if they specify different values for the same setting - ie if you add a new myst extension in one but not the other, does it only take the intersection, the union, just barf, etc? So it might be worth a small amount of time to see if we can figure out how to move totally to conf.py, but I have no idea if it's actually something that CAN work of if you always require config.yml, so not sure worth too too much time.

**Comment by bethac07** [comment]
(the other-other option is to just not make manual changes to conf.py, but figure out what edits need to be made and as part of the build process, regenerate the conf.py, run a small bash script that edits it as needed, and then they can't get out of sync)

**Comment by petebankhead** [comment]
The second option seems to fit with the comment at the top of `conf.py`:
```py
###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
```

The auto-generated `conf.py` seems to have the 'virtue' of being squished together without much spacing, so it's less appealing to manually edit. Which isn't to say I won't forget that one day and try...

Are there docs anywhere on how the files for this PR were generated?

This makes me think that jupyterbook is happier with yaml, then converting to a sphinx configuration at build time: https://jupyterbook.org/en/stable/explain/sphinx.html#how-does-jupyter-book-differ-from-sphinx

And calling
```
jupyter-book config sphinx .
``` 
generates a very similar-looking `conf.py` - so perhaps we could just do that routinely.

**Extra note** I see when I build locally from the PR I get lots of `.doctree` files inside `_build`. Can these be safely `.gitignore`'ed (perhaps ignoring `_build` entirely)?

**Comment by bethac07** [comment]
Hi Pete,

Can't get totally into this now, but quick notes
- [this gist](https://gist.github.com/bethac07/c9428b65c459398fb056b4c03a70218d) goes into how I made this (sorry, thought I sent this by email). There are still some manual edits that need to be made in one of the `pot`s, so we can't fully automate yet, see the last comment there that links to the open issue with jb.
- We can't fully ignore the build folder because that's where the `pot` files live, but we could ignore more of it, feel free to edit (I have "allow maintainer edits to this PR" on)
- The conf.py added here started from running `jb config sphinx`, but if you try to just build from that, it barfs - more info in the gist. That's why I said we'd need a bash script to manually introduce the edits such as adding the path and one thing around that the html directory needs to be in a list, and for some reason exports as a string (that's a bug presumably but haven't had a chance to track down if already reported and report if not)

Realistically, we only need the conf.py for building the `pot` files, so as long as it can do that, if we can confirm that in the normal build process jb takes its own config file over that file in any conflicts, probably safe to have both and the conf.py can safely get a bit out of date. But I haven't had time to get into that (and likely wont' immediately)

**Comment by bethac07** [comment]
Closing in favor of #32

**Pull request closed without merging**
